export const URL_APIS = {
    //Catalogos
    urlAmenidades           : '/api/Amenidades/',
    urlArchivosFiscales     : '/api/ArchivosFiscales/',
    urlBancos               : '/api/Bancos/',
    urlImagenes             : '/api/Imagenes/',
    urlCaracteristicas      : '/api/Caracteristicas/',
    urlAsentamientos        : '/api/Asentamientos/',
    urlClientes             : '/api/Clientes/',
    urlCatalogosSAT         : '/api/CatalogosSAT/',
    urlEmpresas             : '/api/Empresas/',
    urlEmpresaClientes      : '/api/EmpresaClientes/',
    urlIndicadores          : '/api/Indicadores/',
    urlInmobiliarias        : '/api/Inmobiliarias/',
    urlInmobiliariasCliente : '/api/Inmobiliarias/obtenerporcliente/',
    urlClienteMedioContacto : '/api/ClienteMedioContacto/',
    urlEstados              : '/api/Estados/',
    urlMediosContacto       : '/api/MediosContacto/',
    urlMunicipios           : '/api/Municipios/',
    urlPlanes               : '/api/Planes/',
    urlPaquetes             : '/api/Paquetes/',
    urlPaquetesEmpresas     : '/api/PaquetesEmpresas/',
    urlProductos            : '/api/Productos/',
    urlTipoOperacion        : '/api/TipoOperacion/',
    urlTipoCaracteristica   : '/api/TipoCaracteristica/',
    urlTipoPersona          : '/api/TipoPersona/',
    urlTipoPropiedad        : '/api/TipoPropiedad/',
    urlSubTipoPropiedad     : '/api/SubtipoPropiedad/',
    urlTiposAsentamiento    : '/api/TiposAsentamiento/',
    urlTiposFoto            : '/api/TiposFoto/',
    urlEstatus              : '/api/Estatus/',
    urlConfiguracion        : '/api/Configuracion/',
    
    //Busquedas especiales
    urlBusquedasEstado      : '/api/Estados/Municipio/',
    urlBusquedasMunicipio   : '/api/Municipios/Estado/',
    urlBusquedasAsentamiento: '/api/Asentamientos/Estado/Municipio/',
    
    // Procesos
    urlDatosFiscales                : '/api/DatosFiscales/',
    urlPublicaciones                : '/api/Publicaciones/',
    urlPublicacionDetalle           : '/api/PublicacionDetalle/',
    urlPublicacionesMensajes        : '/api/PublicacionesMensajes/',
    urlPublicacionesClienteFiltros  : '/api/PublicacionesClienteFiltros/',
    urlPlanesPaquetesClienteFiltros : '/api/PlanesPaquetesClienteFiltros/',
    urlPublicacionesMensajesFiltros : '/api/PublicacionesMensajesFiltros/',
    urlAmenidadesPublicacion        : '/api/AmenidadesPublicacion/',
    urlFavoritosCliente             : '/api/FavoritosCliente/',
    urlPublicacionMultimedia        : '/api/PublicacionMultimedia/',
    urlMensajesPublicacion          : '/api/MensajesPublicacion/',
    urlPlanesCliente                : '/api/PlanesCliente/',
    urlPaquetesCliente              : '/api/PaquetesCliente/',
    urlPlanesClientePagos           : '/api/PlanesClientePagos/',
    urlPaquetesClientePagos         : '/api/PaquetesClientePagos/',
    urlClientesFacturas             : '/api/ClientesFacturas/',
    urlFacturasClienteFiltros       : '/api/FacturasClienteFiltros/',
    urlContacto                     : '/api/Contacto/',
    urlVistasUsuarios               : '/api/VistasUsuarios/',
    urlEstadisticasCliente          : '/api/EstadisticasCliente/',
    urlEstadisticasClienteFiltros   : '/api/EstadisticasClienteFiltros/',
    urlUbicaciones                  : '/api/Ubicaciones/',
    urlFacturacionExterna           : '/api/FacturacionExterna/',
    
    // Mi cuenta
    // urlPlanesCliente: '/api/PlanesCliente/obtenerporcliente',

    // Auxiliares
    urlLogin                        : '/api/login/'
  };